data_root: /tmp/worker-data
logging:
  level: info
registry:
  url: http://0.0.0.0:6000
storage:
  url: http://0.0.0.0:7000
  access_key: AKIAIOSFODNN7EXAMPLE
  secret_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

containers:
  cpu_sheep_1:
    port: 9001
    type: docker
  cpu_sheep_2:
    port: 9002
    type: docker
